[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
ClientMonitor = 15000
Host = 'edgex-device-mqtt'
Port = 49982
Protocol = 'http'
StartupMsg = 'device mqtt started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'edgex-core-consul'
Port = 8500
CheckInterval = '10s'
FailLimit = 3
FailWaitTime = 10
Type = 'consul'

[Logging]
EnableRemote = false
File = './device-mqtt.log'

[Clients]
[Clients.Data]
Name = 'edgex-core-data'
Protocol = 'http'
Host = 'edgex-core-data'
Port = 48080
Timeout = 50000

[Clients.Metadata]
Name = 'edgex-core-metadata'
Protocol = 'http'
Host = 'edgex-core-metadata'
Port = 48081
Timeout = 50000

[Clients.Logging]
Name = 'edgex-support-logging'
Protocol = 'http'
Host = 'edgex-support-logging'
Port = 48061

[Device]
DataTransform = true
InitCmd = ''
InitCmdArgs = ''
MaxCmdOps = 128
MaxCmdValueLen = 256
RemoveCmd = ''
RemoveCmdArgs = ''
ProfilesDir = '/custom-config'
UpdateLastConnected = false

# Pre-define Devices
[[DeviceList]]
Name = 'pi-136'
Profile = 'Test.Device.MQTT.Pi136.Profile'
Description = 'RaspPi 136'
Labels = ['mqtt', 'raspPi']
[DeviceList.Protocols]
[DeviceList.Protocols.mqtt]

[[DeviceList]]
Name = 'pi-119'
Profile = 'Test.Device.MQTT.Pi119.Profile'
Description = 'RaspPi 119'
Labels = ['mqtt', 'raspPi']
[DeviceList.Protocols]
[DeviceList.Protocols.mqtt]


# Driver configs
[Driver]
IncomingSchema = 'tcp'
IncomingHost = 'mqtt-bridge'
IncomingPort = '1883'
IncomingUser = ''
IncomingPassword = ''
IncomingQos = '0'
IncomingKeepAlive = '3600'
IncomingClientId = 'IncomingDataSubscriber'
IncomingTopic = 'th/#'
ResponseSchema = 'tcp'
ResponseHost = 'mqtt-bridge'
ResponsePort = '1883'
ResponseUser = ''
ResponsePassword = ''
ResponseQos = '0'
ResponseKeepAlive = '3600'
ResponseClientId = 'CommandResponseSubscriber'
ResponseTopic = 'ResponseTopic'
ConnEstablishingRetry = '10'
ConnRetryWaitTime = '5'
